# Generated by Django 3.0.8 on 2020-07-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
